version: '3'
services:
  shoutrrrd:
    image: ghcr.io/adridevelopsthings/shoutrrrd:main
    container_name: shoutrrrd
    restart: on-failure
    volumes:
      - ./services.yaml:/services.yaml
    ports:
      - 8000:80
    
